spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  sql:
    init:
      mode: never
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

---

jwt:
  issuer: ${JWT_ISSUER}
  secret:
    key: ${JWT_SECRET_KEY}
  expiration-time:
    atk: 1800000
    rtk: 86400000